name: Hello world
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-lastest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Run a single  line script
      run: echo "Hello world!"
  
